#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_NONALPHA_WRAP, RENDER_NONALPHA_QUALITY, RENDER_ALPHA , RENDER_ALPHA_UI, RENDER_UI, RENDER_DEBUG, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum SUBSTATE {SUB_NONE, SUB_BEGIN, SUB_END, SUB_MAX };
	//Object Update 리턴값
	enum OBJ_RET {RET_NONE, RET_DEAD, RET_END};

	enum OBJ_ID { OBJ_PLAYER, OBJ_MONSTER, OBJ_BULLET, OBJ_CEILING, OBJ_FLOOR, OBJ_WALL, OBJ_ITEM, OBJ_CAM, OBJ_COL, OBJ_TRIGGER, OBJ_VENDINGMACHINE,OBJ_EFFECT, OBJ_DOOR, OBJ_END };

	enum STATIC_FLOOR_TYPE {
		STATIC_FLOOR = 0,
		STATIC_FLOOR_FLUID,
		STATIC_FLOOR_SLOPE,
		SF_END,
	};

	enum DYNAMIC_FLOOR_TYPE
	{
		// 나중에 앞부분에 정적 텍스처도 추가해야함 
		// ( Collider에 동적 -> 정적 전환 함수 바인딩 (애니메이션 off, 별도 텍스처 출력)) 
		DF_START = 100,
		DYNAMIC_FLOOR_WATER,
		DYNAMIC_FLOOR_LAVA,
		DYNAMIC_FLOOR_ACID,
		DF_END
	};

	enum STATIC_CEILING_TYPE 
	{
		STATIC_CEILING = 0,
		SC_END,
	};

	enum DYNAMIC_CEILING_TYPE 
	{
		// 나중에 앞부분에 정적 텍스처도 추가해야함 
		// ( Collider에 동적 -> 정적 전환 함수 바인딩 (애니메이션 off, 별도 텍스처 출력)) 
		DC_START = 100,
		DYNAMIC_CEILING,
		DC_END
	};

	enum STATIC_WALL_TYPE 
	{
		STATIC_WALL_1 = 0,
		STATIC_WALL_2,
		STATIC_WALL_3,
		STATIC_WALL_4,
		STATIC_WALL_5,
		STATIC_WALL_6,
		STATIC_WALL_7,
		STATIC_WALL_8,
		STATIC_WALL_9,
		STATIC_WALL_10,
		STATIC_WALL_WATER,
		STATIC_WALL_LAVA,
		STATIC_WALL_ACID,
		STATIC_WALL_FENCE,
		STATIC_WALL_SIDEDASH,
		SW_END,
	};

	enum DYNAMIC_WALL_TYPE 
	{
		DYNAMIC_WALL_FAN,
		DYNAMIC_WALL_FAN_BLOOD,
		DW_END
	};

	enum MOVE_DIR { DIR_NONE, DIR_UP, DIR_DOWN, DIR_LEFT, DIR_RIGHT, DIR_LEFTUP, DIR_LEFTDOWN, DIR_RIGHTUP, DIR_RIGHTDOWN };

	enum PLAYER_STATE : byte
	{
		IDLE = 1,
		RELOAD = 2,
		ATTACK = 3,
		KICK = 5,
		DRINK = 6,
		SLIDE = 7,
		INTRO = 8,
		SHOP  = 9,
		READY_NEXT,
		TAKEDOWN,
		MAIN_END
	};

	enum WEAPON_STATE : byte
	{
		WEAPON_NONE = 0,
		WEAPON_PISTOL = 1,
		WEAPON_SHOTGUN = 2,
		WEAPON_KATANA = 3,
		WEAPON_END
	};

	enum COLLIDER_TAG { TAG_NONE, TAG_KICK, TAG_SLIDE, TAG_WATER, TAG_LAVA, TAG_ACID, TAG_ELECTRIC, TAG_KATANA, TAG_SLOPE, TAG_SIDE_DASH_X, TAG_SIDE_DASH_Z, TAG_HEAD, TAG_TAKEDOWN,TAG_AXE,TAG_DRINK,TAG_FAN, TAG_END };
	enum COL_DIR { CDIR_NONE, CDIR_X, CDIR_Y, CDIR_Z, CDIR_END };

	//본게임에서는 EVENT_DOOR_OPEN, 지금은 임시로 In, out 으로 사용
	enum EVENT_TYPE { 
		EVENT_MONSTER_DEAD,
		EVENT_ROOM_CHANGE,
		EVENT_DOOR_OPEN,
		EVENT_STAGE_START,
		EVENT_STAGE_END,
		EVENT_READY_NEXT_STAGE,
		EVENT_NEXT_STAGE,
		EVENT_ENDING,
		EVENT_TAKEDOWN,
		EVENT_TAKEDOWN_END,
		EVENT_DRINK,
		EVENT_END };

	// SLOPE 방향 설정
	enum SLOPE_DIR
	{
		SLOPE_POSITIVE_X,
		SLOPE_NEGATIVE_X,
		SLOPE_POSITIVE_Z,
		SLOPE_NEGATIVE_Z,
		SLOPE_DIR_END
	};

	enum UI_STATE
	{
		UI_DEFAULT = 0,
		UI_STAGE_CLEAR,
		UI_DEACTIVATE,
		UI_TAKEDOWN,
		UI_END
	};

	enum TRIGGER_TYPE
	{
		TRIGGER_ROOM_CHANGE,
		TRIGGER_STAGE_END,
		TT_END
	};

	enum FONT_TYPE
	{
		FONT_DEFAULT,
		FONT_NUMBER,
		FONT_WORD,
		FONT_LARGEWORD,
		FONT_LARGENUMBER,
		FONT_SMALLNUMBER,
		FONT_END
	};

	enum OBJ_ITEM_TYPE
	{
		ITEM_NONE,
		ITEM_SODA,
		ITEM_SODAMACHINE,
		ITEM_AXE,
		ITEM_EXTINGUISHER,
		ITEM_END
	};

	enum DOOR_TYPE
	{
		DOOR_1,
		DOOR_2,
		DOOR_3,
		DOOR_ELEVATOR,		 
		DT_END
	};
	enum CHANNELID
	{
		SOUND_MASTER,
		SOUND_PLAYER,
		SOUND_PLAYER_BGM,
		SOUND_MONSTER,
		SOUND_WEAPON,
		SOUND_SFX,
		SOUND_BGM,
		SOUND_END
	};

	//SCENE_TUTORIAL 맵로더 호환용으로 놔둠 
	//enum SCENE_TYPE { SCENE_NONE, SCENE_MENU, SCENE_TUTORIAL, SCENE_BATTLE, SCENE_BOSS, SCENE_END };
	enum SCENE_TYPE { SCENE_NONE, SCENE_LOGO, SCENE_TUTORIAL, SCENE_BATTLE, SCENE_BOSS, SCENE_ENDING, SCENE_ROAD, SCENE_CREDIT, SCENE_END };
}
#endif // Engine_Enum_h__
