#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA,  RENDER_ALPHA , RENDER_ALPHA_UI, RENDER_UI,RENDER_DEBUG, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum SUBSTATE {SUB_NONE, SUB_BEGIN, SUB_END, SUB_MAX };
	//Object Update 리턴값
	enum OBJ_RET {RET_NONE, RET_DEAD, RET_END};

	enum OBJ_ID {OBJ_PLAYER, OBJ_MONSTER, OBJ_BULLET, OBJ_TERRAIN, OBJ_ITEM, OBJ_CAM, OBJ_COL, OBJ_OBSTACLE, OBJ_END };

	enum TERRAIN_TYPE { TERRAIN_FLOOR, TERRAIN_CEILING, TERRAIN_WALL, TERRAIN_END };

	enum MOVE_DIR { DIR_NONE, DIR_UP, DIR_DOWN, DIR_LEFT, DIR_RIGHT, DIR_LEFTUP, DIR_LEFTDOWN, DIR_RIGHTUP, DIR_RIGHTDOWN };
}
#endif // Engine_Enum_h__
